filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/nginx/*.log

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  username: "elastic"
  password: "viWmk2XOXFGjiOtXNMr6"

setup.kibana:
  host: "http://kibana:5601"
  username: "kibana_system"
  password: "UVbnUahs5TR5J5ntHeGj"